### ISSUE TITLE
Possible bug in `model.diffusion.diffusion_ppo.PPODiffusion`

### ISSUE THREAD

**Issue by acl21** [irom-princeton/dppo#17]
Hi there, when fine-tuning with BC loss regularization, I ran into a bug. 

In `loss` function of  `model.diffusion.diffusion_ppo.PPODiffusion` [here](https://github.com/irom-princeton/dppo/blob/7b10df690d54f3d29524f20daa8cf78288a21a9b/model/diffusion/diffusion_ppo.py#L109), I think `self.forward` accepts `obs` as-is (i.e. as a `dict`). Also, `obs["state"]`  is already in `B x horizon x obs_dim` shape so maybe the unsqueezing is also not necessary. Hopefully, I made sense. 

I understand this is rather trivial, but I figured I should let you know. Once again, thank you for such a well-maintained code base!

**Comment by allenzren** [comment]
Thanks for pointing out! We didn't test the bc loss after code refactoring. It should be fixed now.
