### ISSUE TITLE
When the number of excutable actions is larger than 1

### ISSUE THREAD

**Issue by he-nantian** [irom-princeton/dppo#19]
I wonder when the number of excutable actions is larger than 1 (such as 2 with the planning horizon of 8), does it continuously excutes 2 actions and gets two rewards to tune its parameters?

**Comment by allenzren** [comment]
Yes, the multi-step wrapper will run two actions continuously and [accumulate](https://github.com/irom-princeton/dppo/blob/dc8e0c9edce7ac2b2ff112abe460e1c21b0b3bdc/env/gym_utils/wrapper/multi_step.py#L170) the rewards over the two steps. You can modify the wrapper to your needs.

**Comment by he-nantian** [comment]
I’m grateful for your quick response! It’s a big help—thank you!
