### ISSUE TITLE
Environmental Issues

### ISSUE THREAD

**Issue by NotOneRing** [irom-princeton/dppo#22]
Dear Allen,

I have encountered some environmental issues as follows:

wget https://iai-robust-rearrangement.s3.us-east-2.amazonaws.com/IsaacGym_Preview_4_Package.tar.gz
--2024-11-12 14:55:31--  https://iai-robust-rearrangement.s3.us-east-2.amazonaws.com/IsaacGym_Preview_4_Package.tar.gz
Resolving iai-robust-rearrangement.s3.us-east-2.amazonaws.com (iai-robust-rearrangement.s3.us-east-2.amazonaws.com)... 3.5.130.162, 3.5.132.131, 52.219.179.138, ...
Connecting to iai-robust-rearrangement.s3.us-east-2.amazonaws.com (iai-robust-rearrangement.s3.us-east-2.amazonaws.com)|3.5.130.162|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-11-12 14:55:32 ERROR 404: Not Found.

git clone git@github.com:ankile/furniture-bench.git
Cloning into 'furniture-bench'...
The authenticity of host 'github.com (20.205.243.166)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights

I would really appreciate any suggestions you could provide!

**Comment by allenzren** [comment]
Ah thanks for pointing this out! It looks the link is updated and you can try `wget https://iai-robust-rearrangement.s3.us-east-2.amazonaws.com/packages/IsaacGym_Preview_4_Package.tar.gz`
