### ISSUE TITLE
problem when reproducing furniture task

### ISSUE THREAD

**Issue by seagul1** [irom-princeton/dppo#28]
Thanks for your great work! When I want to finetune furniture task, there occur some problem, it seems the furniture bench I cloned lacks **furniture_rl_sim_env**
![image](https://github.com/user-attachments/assets/351b571b-7895-4c4e-8223-2f1c41e6b5ae)
What should I do to fix it?

**Comment by allenzren** [comment]
Hey, if you cloned this repo based on our [instruction](https://github.com/ankile/furniture-bench/blob/52e7c686a16b10615539ec480694ef95f69dfe43/furniture_bench/envs/furniture_rl_sim_env.py#L1689), the class should be here? https://github.com/ankile/furniture-bench/blob/52e7c686a16b10615539ec480694ef95f69dfe43/furniture_bench/envs/furniture_rl_sim_env.py#L1689

**Comment by allenzren** [comment]
I guess you cloned the original furniture-bench repo instead. https://github.com/clvrai/furniture-bench/tree/main/furniture_bench/envs

**Comment by seagul1** [comment]
Oh! I I did clone the original repo, Thank you very much for your answer!
